[build]
  command = "ng build --prod && npm run json-server"
  publish = "dist/EventXplorer"

[dev]
  command = "ng serve --open"

[[redirects]]
  from = "/api/*"
  to = "http://localhost:3000/users/:splat"
  status = 200